feat: eu filetypes and iana mediatypes aggregation and filter
Informasjonsforvaltning/fdk-fulltext-search pull request #161
Opened 2021-09-07 13:21 UTC by jeffreiffers

Fixes #160

2021-09-07 13:54 UTC, NilsOveTen commented on tests/mock_data/data-service-json-size.json
> -            "id": "baaeeaf2-a2d0-44d0-a5a9-d040a66993e2",
Her i mock_data har du endret veldig mange "id" til "uri", etter som jeg ser så er det bare et fåtall som faktisk skal endres

2021-09-08 10:10 UTC, jeffreiffers commented on tests/mock_data/data-service-json-size.json
> -            "id": "baaeeaf2-a2d0-44d0-a5a9-d040a66993e2",
Skal være korrigert.

2021-09-08 10:20 UTC, NilsOveTen commented on tests/mock_data/data-service-json-size.json
> -            "id": "baaeeaf2-a2d0-44d0-a5a9-d040a66993e2",
Ikke som jeg ser

2021-09-08 10:38 UTC, NilsOveTen requested changes

2021-09-08 10:38 UTC, NilsOveTen commented on tests/mock_data/data-service-json-size.json
> +            "uri": "baaeeaf2-a2d0-44d0-a5a9-d040a66993e2",
```suggestion
            "id": "baaeeaf2-a2d0-44d0-a5a9-d040a66993e2",
```

2021-09-08 10:38 UTC, NilsOveTen commented on tests/mock_data/data-service-json-size.json
> +                "uri": "910244132",
```suggestion
                "id": "910244132",
```

2021-09-08 10:38 UTC, NilsOveTen commented on tests/mock_data/data-service-json-size.json
> +            "uri": "7c927741-59b5-4511-855f-54ab52f8baa0",
```suggestion
            "id": "7c927741-59b5-4511-855f-54ab52f8baa0",
```

2021-09-08 10:38 UTC, NilsOveTen commented on tests/mock_data/data-service-json-size.json
> +                "uri": "910258028",
osv

2021-09-08 10:38 UTC, NilsOveTen commented on tests/mock_data/data-service.json
> +            "uri": "baaeeaf2-a2d0-44d0-a5a9-d040a66993e2",
```suggestion
            "id": "baaeeaf2-a2d0-44d0-a5a9-d040a66993e2",
```

2021-09-08 10:38 UTC, NilsOveTen commented on tests/mock_data/data-service.json
> +                "uri": "910244132",
```suggestion
                "id": "910244132",
```

2021-09-08 10:38 UTC, NilsOveTen commented on tests/mock_data/data-service.json
> +            "uri": "7c927741-59b5-4511-855f-54ab52f8baa0",
osv

2021-09-08 10:38 UTC, NilsOveTen commented on tests/mock_data/example_response.json
> +      "uri": "0670b703-e230-42ec-967e-27fe11ed3a69",
```suggestion
      "id": "0670b703-e230-42ec-967e-27fe11ed3a69",
```

2021-09-08 10:38 UTC, NilsOveTen commented on tests/mock_data/example_response.json
> +          "uri": "910244132",
```suggestion
          "id": "910244132",
```

2021-09-08 10:38 UTC, NilsOveTen commented on tests/mock_data/example_response.json
> +      "uri": "d84027ac-fabc-4c50-b729-a61c6e34683b",
osv

2021-09-08 11:43 UTC, jeffreiffers commented on tests/mock_data/data-service-json-size.json
> +                "uri": "910258028",
```suggestion
                "id": "910258028",
```

2021-09-08 11:55 UTC, NilsOveTen approved these changes

2021-09-10 06:00 UTC, oyvindis commented on src/fdk_fulltext_search/ingest/__init__.py
> +                        ArrayList formats = new ArrayList();
Dette er duplisert kode som brukes likt både for dataset og dataservice, bør lages som en funksjon som da vedlikeholdes et sted.

2021-09-10 06:27 UTC, oyvindis commented on docker-compose.yml
> +        - NEW_REFERENCE_DATA_BASE_URI=http://servicesmock:8080/new-reference-data
Ser ikke at denne blir brukt.

2021-09-10 06:38 UTC, oyvindis approved these changes

2021-09-10 06:48 UTC, NilsOveTen commented on docker-compose.yml
> +        - NEW_REFERENCE_DATA_BASE_URI=http://servicesmock:8080/new-reference-data
Den blir brukt av rdf-parser

2021-09-16 10:41 UTC, merged