chore: use alias for indices
Informasjonsforvaltning/fdk-fulltext-search pull request #70
Opened 2020-09-23 13:39 UTC by NilsOveTen

Med dette så venter fulltext til ny index er klar før den sletter gammel og tar ny i bruk

2020-09-23 13:43 UTC, azaxarov approved these changes
Nice!

2020-09-24 05:09 UTC, NilsOveTen commented
Alle-søket i staging ble jo spennende...

Slettinga jeg gjorde fjernet tydeligvis bare aliaset fra indeksen, men indeksen ble liggende, så nå har vi 100000+ datasett i alle-søket :)

Rimelig sikker på at jeg har fiksa det, men fiksen fjerner ikke det som allerede er oppretta i staging, blir i det minste ikke flere nå. Skal få Hans Olav til å slette litt.

![Screenshot from 2020-09-24 07-04-13](https://user-images.githubusercontent.com/50194012/94103189-45249000-fe34-11ea-98a5-923d8386812d.png)

2020-09-24 07:17 UTC, rannveigskjerve requested changes

2020-09-24 07:17 UTC, rannveigskjerve commented on src/ingest/__init__.py
> +    logging.info("creating {0}".format(new_index_name))
f"creating {new_index_name}"

2020-09-24 07:28 UTC, NilsOveTen commented on src/ingest/__init__.py
> +    logging.info("creating {0}".format(new_index_name))
fix'nd-ed

2020-09-24 08:13 UTC, rannveigskjerve approved these changes

2020-09-24 09:54 UTC, merged